title: BenchGen # your name (or website title) here
logo: "/images/BenchGenLogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <p style="text-align:justify;">The BenchGen project aims to synthesize programs that are sufficiently expressive to stress-test computing systems, such as operating systems, compiler optimizations, memory allocation libraries and even computer architectures.<p><br><br>
theme: jekyll-theme-minimal

colors:
  crimson: '#900C3F'
